server:
  port: 8761
eureka:
  instance:
    hostname: server.eureka.svc
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
